CREATE TABLE customer (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR2(50) UNIQUE NOT NULL,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    market_segment VARCHAR2(30),
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

