CREATE TABLE customer (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    churn_value NUMBER
);

INSERT INTO customer (name, churn_value) VALUES ('Juan', 0.4);
INSERT INTO customer (name, churn_value) VALUES ('María', 0.7);
INSERT INTO customer (name, churn_value) VALUES ('Rodrigo', 0.8);