CREATE TABLE churn_history (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER(19,0) NOT NULL,
    request_id VARCHAR2(64) NOT NULL UNIQUE,
    api_provider VARCHAR2(50) NOT NULL,
    churn_score NUMBER(5,2),
    risk_level VARCHAR2(20) NOT NULL,
    http_status NUMBER(3) NOT NULL,
    response_time_ms NUMBER,
    raw_response CLOB,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);
